admin:
  existingSecret: grafana-admin-secret
  userKey: username
  passwordKey: password

service:
  type: NodePort

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://my-prometheus-server.monitoring.svc.cluster.local
        isDefault: true
        editable: true

grafana.ini:
  smtp:
    enabled: true
    host: smtp.mail.ru:587
    user: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    from_address: "mykola.nmn@gmail.com"
    from_name: Grafana
    skip_verify: true
    startTLS_policy: OpportunisticStartTLS

env:
  SMTP_USER:
    valueFrom:
      secretKeyRef:
        name: grafana-smtp-secret
        key: smtp_user
  SMTP_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: grafana-smtp-secret
        key: smtp_password


extraVolumeMounts:
  - name: grafana-alerting-provisioning
    mountPath: /etc/grafana/provisioning/alerting
    readOnly: true

extraVolumes:
  - name: grafana-alerting-provisioning
    configMap:
      name: grafana-alerting-provisioning
